hl.on("hyprland.start", function()
    --    hl.exec_cmd("noctalia")
    --    hl.exec_cmd("waybar")
    hl.exec_cmd("qs -c caelestia")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("music_presence")
    hl.exec_cmd("python3 ~/scripts/infinite_desktop_core.py 1.6 > /tmp/infinite-desktop.log 2>&1")
end)
