preload = /home/painter/Pictures/Wallpapers/wallhaven_1jqmvv.jpg
wallpaper {
    monitor = eDP-1
    path = /home/painter/Pictures/Wallpapers/wallhaven_1jqmvv.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/painter/Pictures/Wallpapers/wallhaven_1jqmvv.jpg
    fit_mode = cover
}
